name: noo_sms
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.5
  get: ^4.6.6
  hive: ^2.2.3
  http: ^1.1.1
  intl: ^0.19.0
  onesignal_flutter: ^5.2.2
  path: ^1.8.3
  path_provider: ^2.1.5
  # provider: ^6.1.2
  shared_preferences: ^2.2.3
  get_storage: ^2.1.1
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.3
  search_choices: ^2.2.3
  dio: ^5.4.0
  money_formatter: ^0.0.6
  flutter_screenutil: ^5.9.3
  image_picker: ^1.0.8
  image: ^4.3.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1
  sembast: ^3.8.0
  signature: ^5.5.0
  async: ^2.12.0
  flutter_svg: ^2.0.17
  mockito: ^5.4.4
  whatsapp_unilink: ^2.1.0
  google_maps_flutter: ^2.10.1
  file_picker: ^10.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: any 
  build_runner: ^2.4.9 
  analyzer: ^6.2.0
   

flutter:
  uses-material-design: true
  assets:
    - assets/icons/noo_icon.svg
    - assets/icons/sample_order_icon.svg
    - assets/icons/sms_icon.svg
    - assets/icons/customer_visit.svg
    - assets/icons/logo.png
    - assets/icons/asset_submission_icon.svg
    - assets/icons/catalog.svg
    - assets/icons/edit_table.svg
    - assets/icons/order_tracking _icon.svg
    
